baseurl = "/"
languageCode = "en-us"
title = "Xaringan themes"
theme = "hugo-owaraiclub"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 24


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.side]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.side]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.side]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    footer = "a fancy footer"
[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "author"
