---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, Inc."
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
draft: true
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

---

## use_theme!

```{r echo=TRUE}
use_theme = function(theme = "tcgriffith/xaringan_theme_example", ref =
                              "master") {
  bn = basename(theme)
  
  builtin_css = xaringan:::list_css()
  builtin_theme = names(builtin_css)
  
  if (theme %in% builtin_theme) {
    css_local = builtin_css[theme]
  } else{
    css_remote = sprintf("https://raw.githubusercontent.com/%s/%s/%s.css",
                         theme,
                         ref,
                         bn)
    xfun::download_file(css_remote)
    css_local = basename(css_remote)
  }
  
  htmltools::includeCSS(css_local)
}

use_theme('middlebury')
```

---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

???

Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---
class: center, middle

# xaringan

### /ʃaː.'riŋ.ɡan/


---
class: bg-red

# I am red!


---
class: bg-bisque

# I am bisque!

---
class: bg-blue

# I am blue, 

# if it's not blue, you are using an old version of the theme!

the init version doesn't have blue!



